import Harsh from "../assets/team pictures/HARSH SINGH.jpg";

const TeamInfo = {
  faculty: {
    name: "Dr. Apurv Ashish",
    post: "Faculty Advisor",
    image: Harsh,
  },

  members: [
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "",
      instagramLink: "",
      linkedinLink: "",
    },
  ],
};

export default TeamInfo;
