import Harsh from "../assets/team pictures/HARSH SINGH.jpg";

const TeamInfo = {
  faculty: {
    name: "Dr. Apurv Ashish",
    post: "Faculty Advisor",
    image: Harsh,
  },

  members: [
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "https://www.facebook.com/harsh.singh.353803/",
      instagramLink: "https://www.instagram.com/harsh999924/",
      linkedinLink: "https://www.linkedin.com/in/harsh-singh-bit/",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: Harsh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
  ],
};

export default TeamInfo;
