import HarshSingh from "../assets/team pictures/HarshSingh.jpeg";
import ShailendraKumar from "../assets/team pictures/ShailendraKumar.jpg";

const TeamInfo = {
  faculty: {
    name: "Dr. Apurv Ashish",
    post: "Faculty Advisor",
    image: HarshSingh,
  },

  members: [
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "https://www.facebook.com/harsh.singh.353803/",
      instagramLink: "https://www.instagram.com/harsh999924/",
      linkedinLink: "https://www.linkedin.com/in/harsh-singh-bit/",
    },
    {
      name: "Shailendra Kumar",
      post: "Joint President",
      image: ShailendraKumar,
      facebookLink: "/#team",
      instagramLink: "https://instagram.com/arto_grapher_",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
    {
      name: "Harsh Singh",
      post: "President",
      image: HarshSingh,
      facebookLink: "/#team",
      instagramLink: "/#team",
      linkedinLink: "/#team",
    },
  ],
};

export default TeamInfo;
